<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('helloswigc')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_helloswigc.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('helloswigc.so')) return;
    } else {
      if (!dl('helloswigc.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class helloswigc {
	const TEST = TEST;

	static function showHelloSwigC() {
		return showHelloSwigC();
	}

	static function echoStringC($str) {
		return echoStringC($str);
	}
}

/* PHP Proxy Classes */

?>
