<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('helloswigcpp2')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_helloswigcpp2.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('helloswigcpp2.so')) return;
    } else {
      if (!dl('helloswigcpp2.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



/* PHP Proxy Classes */
class HelloSwigCls {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_helloswigcpp2_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_helloswigcpp2_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function showHelloSwigCpp() {
		return HelloSwigCls_showHelloSwigCpp($this->_cPtr);
	}

	function showPassedStrCpp($str) {
		return HelloSwigCls_showPassedStrCpp($this->_cPtr,$str);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_HelloSwigCls') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_HelloSwigCls();
	}
}


?>
